### ISSUE TITLE
create a set format for documentation

### ISSUE THREAD

**Issue by fnriv** [cse110-sp23-group3/cse110-sp23-group3#13]
[reference to 8ball documentation issue](https://github.com/cse110-sp23-group3/8-ball/issues/4)

do we want to keep this documentation? i think we definitely should establish a template to refer to here (even if it's the same as last) but not sure if more should be added because it's a bigger project.

if anyone has experience from internships or other projects please contribute !

**Comment by nsyousef** [comment]
I updated the action in Big Project Playground so that it will run whenever someone pushes a new tag with the format vX.Y.Z to the repo. It is supposed to include any commits between the latest tag and the second-to-latest tag in the release notes, which it adds to the bottom of the README. However, it doesn't seem to get the second to last tag properly. It keeps setting the variables LATEST_TAG and SECOND_TO_LAST_TAG to the latest tag (i.e. the one just pushed). Because they are set to the same tag, the release notes end up being empty, with only the title and a single empty bullet point being added to the README. I have not figured out how to fix this bug yet. 

BTW, this version of the GitHub action can be found in the releasenotestest branch of the Big Project Playground.

**Comment by phuanh004** [comment]
> I updated the action in Big Project Playground so that it will run whenever someone pushes a new tag with the format vX.Y.Z to the repo. It is supposed to include any commits between the latest tag and the second-to-latest tag in the release notes, which it adds to the bottom of the README. However, it doesn't seem to get the second to last tag properly. It keeps setting the variables LATEST_TAG and SECOND_TO_LAST_TAG to the latest tag (i.e. the one just pushed). Because they are set to the same tag, the release notes end up being empty, with only the title and a single empty bullet point being added to the README. I have not figured out how to fix this bug yet.
> 
> BTW, this version of the GitHub action can be found in the releasenotestest branch of the Big Project Playground.

Check it out to see if it works with my latest commit Nick

**Comment by nsyousef** [comment]
Still not working. I will try to figure it out today.

**Comment by phuanh004** [comment]
Hmm, what is the current status and what you expect it to be?

**Comment by nsyousef** [comment]
So I am trying to make it so that every time a new tag is pushed to GitHub, the action runs. It takes all the commits between the tag that was just pushed and the tag just before it and formats them into release notes, which it adds to the README file. The trouble is, the command to get the second-to-latest tag and store it in the variable `SECOND_TO_LAST_TAG` seems to be getting the latest tag instead of the second-to-latest, based on the output I am seeing when the GitHub action runs. However, when I try the same command in my terminal on my laptop, it seems to get the second-to-last tag just fine. So I am trying to figure out why that is and how I can fix it. I am trying to make it so that the variable  `SECOND_TO_LAST_TAG` holds the second-to-latest tag. For instance, if the latest two tags are `v3.0.4` and `v3.0.3`, `SECOND_TO_LAST_TAG` should store `v3.0.3`

If you are going to take a look at it, please git pull first since I messed around with it a bit. I tried the command that was there when you added the parenthesis on my laptop and it actually outputted the latest tag, so I changed it to a command that, on my laptop, outputs the second to latest tag.

**Comment by nsyousef** [comment]
Never mind. I resolved the issue where `SECOND_TO_LAST_TAG` was set improperly.

**Comment by phuanh004** [comment]
Hmm, interesting, when adding the fetch depth solve that, since the HEAD
command works for me on the cli but not here… Well done anyways!

**Comment by nsyousef** [comment]
Alright. I have the final version of the GitHub action to generate release notes from commits working. Here is how to use it:

Versions will be tagged with the following format: vX.Y.Z. X, Y, and Z are all integers greater than or equal to zero. Version numbers should follow the SemVer rules (https://semver.org/). Whenever a new version is completed, create a Git tag with the correct version number (e.g. v1.3.2) and push that tag to the repo. The GitHub action will automatically generate the release notes from the commits between the tag you just pushed and the previously pushed tag. 

In order for commits to appear in the release notes, they must be in the following format. They must start with either `feat: `, `fix: `, or `doc: `. Any text after that will appear in the release notes exactly as written in the commit message. For example, commit messages might look like this:

`feat: add login screen`
`fix: user not able to click send button after refreshing page`
`doc: added documentation for function readFortune()`

Commits not following that format will not appear in the release notes.

Commit messages beginning with `feat: ` will be preceded by **Feature:** in the release notes. Commits beginning with `fix: ` will be preceded by **Bug Fix: **. Commits beginning with `doc: ` will be preceded by **Documentation: **.  The above sample commits would look like this in the release notes:

> **Feature:** add login screen
> **Bug Fix:** user not able to click send button after refreshing page
> **Documentation: ** added documentation for function readFortune()

A header above each set of release notes will say the version number to which the release notes apply. For example, if the most recent tag pushed was `v1.2.3`, the release notes would appear under the following header:

## v1.2.3

Please check out the big project playground for the full action. If you have any feedback about this system of generating release notes, please contact me. Otherwise, we can integrate the GitHub action into the main repo.

**Comment by phuanh004** [comment]
^ Looks good at the moment, Nick!

**Comment by nsyousef** [comment]
Sounds good. I know we were talking about putting the names of the people who made the commits into the release notes. Do you guys want to do that or should we just leave it as is for now?

**Comment by phuanh004** [comment]
I'm okay with that. But I'm not sure if we can do it right for the first time with the pull request. Can you be the main review of the first version's pull request to main so we can follow up after that.

**Comment by nsyousef** [comment]
Ok. Yeah, I could review the first version's pull request to main. Although since I was the one that created the action, I feel like someone else should review the pull request as well.

**Comment by nsyousef** [comment]
Actually, since I created the pull request it won't let me add myself as a reviewer. Someone else will probably have to do it. If there are any issues with merging the release notes generator into main, please let me know.

**Comment by phuanh004** [comment]
Yeah, I looked at your action in the playground before, I will take a look at ur pull request.

**Comment by phuanh004** [comment]
Hmm, @nsyousef, do you think that we should change the changelog to just `CHANGELOG.md` and then readme for other information?

E.g. https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md

**Comment by nsyousef** [comment]
Sure, we can do that. That way the README does not get super long. I can update the action on the readme-updates branch and either remove the Release Notes header from the README or include a link in the README to the CHANGELOG.md file.

**Comment by nsyousef** [comment]
Alright. Pushed the changes.

**Comment by nsyousef** [comment]
Decided to close this at our Milestone 2 Recap (was supposed to be closed with merge of new README and release notes generator). If there are any other issues with documentation, please feel free to either reopen this and comment on the documentation issues or create a new issue. Thank you.
