### ISSUE TITLE
how are we going to test code?

### ISSUE THREAD

**Issue by fnriv** [cse110-sp23-group3/cse110-sp23-group3#19]
open for discussion but necessary for milestone 1 and #18

**Comment by fnriv** [comment]
move and discuss to milestone 2, turn into adr

**Comment by MichaelYe48** [comment]
Nick and I are currently writing extensive unit tests for most of the functions we have.

**Comment by nsyousef** [comment]
Here is a current update on the tests.

There are 3 test files located in `source/__tests__`. The file `index.test.js` runs contains the E2E tests. The files `mock.unit.test.js` and `nomock.unit.test.js` contain unit tests. I commented out all of the unit tests that fail, which are in `mock.unit.test.js`. All the tests in `nomock.unit.test.js` pass on my machine. The reason I created two files was because I wanted to use one of the files to create mock functions and the other one for tests that did not require mock functions. Unfortunately, I still did not solve the problem I was having. So we can delete `mock.unit.test.js` if you all want to.

The tests in `index.test.js` are inconsistent. Sometimes `Check that all profiles are present in the grid` and `Check that all full length profiles are present` pass and sometimes they fail (there are two of each, so four total). I suspect it is because things are not loaded before they are checked for because without changing any code, sometimes they pass and sometimes they fail. We wrote similar tests in Lab 8 and I think I had the same issue, but I never figured out how to fix it. We can delete those tests if you all want to, but right now I have them in there and they do run.

If you guys want, we can jump on a quick call or text in Slack or here to confirm what we are going to do from here. Let me know, either here or in my slack message that I will send (or have sent) linking to this message.

**Comment by henryzhang03** [comment]
@nsyousef i believe it is because it is in the shadow dom, i keep getting the error:

```
    TypeError: Cannot read properties of null (reading 'name')

      34 |       data = await profilesGrid[i].getProperty('data');
      35 |       plainValue = await data.jsonValue();
    > 36 |       if (plainValue.name.length === 0) {
         |                      ^
      37 |         allArePopulated = false;
      38 |       }
      39 |       if (plainValue.role.length === 0) {

      at Object.name (source/__tests__/index.test.js:36:22)
```

**Comment by fnriv** [comment]
closing as we are finished coding and discussed testing in meetings
