### ISSUE TITLE
Bug: chat typing issues

### ISSUE THREAD

**Issue by nsyousef** [cse110-sp23-group3/cse110-sp23-group3#48]
Steps to reproduce:

1) From the screen where Simba asks "Would you like me to read your palm?", type something into the box and hit enter or click "send":
![Screenshot 2023-06-01 at 12 21 08 AM](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/114201888/cb866723-e9c3-44f3-bd56-f76999b66ff4)

What happens:

After you hit enter or click "send" an error 405 occurs and the user is presented with a blank page:
![Screenshot 2023-06-01 at 12 25 21 AM](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/114201888/0303294b-d9e2-4136-b7e2-0a29fba70c79)

**Comment by nsyousef** [comment]
Works a little bit better. However, there are still a few issues:

![Screenshot 2023-06-01 at 1 36 43 AM](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/114201888/02b8785a-f567-42ad-b906-950b69ebf903)

If the user types their responses to the questions instead of clicking the buttons, you get to a message where it says "The undefined undefined". If you click "yes" then type something random for the second question, it says "The yes undefined".

![Screenshot 2023-06-01 at 1 39 50 AM](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/114201888/7ae28d4e-938d-4f2c-9930-b2a0c22ff392)

**Comment by nsyousef** [comment]
Also, once you get to this step:
![Screenshot 2023-06-01 at 1 43 28 AM](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/114201888/8225d8f7-c78a-4972-b51c-edaca4390836)

if you type something and hit enter or send it gives the same error 405 as before.
![Screenshot 2023-06-01 at 1 45 05 AM](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/114201888/c83e1802-8a94-4918-bfba-d2e79df24e27)

**Comment by phuanh004** [comment]
Good catch! Hard coding in 3 steps cause this problem. 
Probably need a solution for this @henryzhang03

**Comment by henryzhang03** [comment]
I'll fix it in my next commit, am aware of this but did not bother when coding the first version

**Comment by lemangomeister** [comment]
To what extent do we have input validation, if we have any?

**Comment by henryzhang03** [comment]
@lemangomeister we have no input validation on the client side but as for the server side api, i added a simple xss check as you can see in the other repo: https://github.com/cse110-sp23-group3/AI-API that we call. it is hard to do subjective input validation when it is a chat feature. You can look for some bad words or some stuff that can break the api, but otherwise, I'm open to suggestions

**Comment by lemangomeister** [comment]
I'm not familiar with working with APIs at all so I'm gonna sound pretty ignorant but, how difficult is it to implement a change so that something like this doesn't happen?:
![image](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/69333304/ed25b7cf-e04e-4f4a-b775-f190c67ef72b)

Where info not relating to palm reading won't be concatenated to the overall reading

**Comment by henryzhang03** [comment]
no longer relevant
