### ISSUE TITLE
"New Chat" button DOES create a new chat even though the user has not submitted any input yet.

### ISSUE THREAD

**Issue by lemangomeister** [cse110-sp23-group3/cse110-sp23-group3#59]
**history-crud-function** branch
Steps to reproduce:
-Have a new unused page
![image](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/69333304/6bffb21d-7368-42b7-9553-91035bc2f4d1)

-Press "New Chat"
-Refresh
![image](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/69333304/a463c1e2-f0f7-44a4-95d0-ba85b7b9532d)

**Comment by lemangomeister** [comment]
Collaborating with Michael on this right now

**Comment by lemangomeister** [comment]
Main issue we found:
The "New Chat" button functionality does too many things. What we mean is that we can't just disable it (i.e. prevent the user from clicking it) without negatively affecting the rest of the functionality of the app.

**Comment by nsyousef** [comment]
I think one of the things that makes it buggy is the fact that the buttons that show up in the side bar are not always consistent with how many chats actually exist. I think it would help to make it so that all the existing chats are saved in one place (e.g. local storage) and any chat not in that place does not exist. It would also help to always keep the chat history buttons in sync with whatever is in local storage. 

It also might help if, when the user first opens the page, the chat is automatically saved to local storage immediately, even before the user clicks 'yes' to answer the question "Would you like me to read your palm?" In fact, we may not even need that first question. We can just skip to the question "Which palm line would you like me to read? Select from the buttons below." I feel like it doesn't make sense to select "no" to that first question. If you do that, you might as well not use the app at all. When the user loads the page for the first time (i.e. with an empty local storage), the chat should probably already be saved to local storage and a (disabled) button should be created in the side bar for that conversation. On subsequent page loads, you can either create a new chat or load an existing one, but if you create a new one be sure to add it to the side bar and save it with the others immediately.

Hope that helps!

**Comment by henryzhang03** [comment]
@nsyousef this is what is intended, but when implementing I had some issues. I do think however that we should keep a sort of "state" variable that represents what we will need to save to local storage at the end of a session. I will continue tomorrow and fix the bugs.

**Comment by dolivares11** [comment]
Is there some place where we have the intended behavior clearly imaged for us?

**Comment by lemangomeister** [comment]
> Is there some place where we have the intended behavior clearly imaged for us?

I don't quite know where it is formally, but I just happen to hover over a piece of code and saw Henry's comments
![image](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/69333304/de8a1cf0-b3fa-4bd2-8f1a-524e92719f2c)

**Comment by henryzhang03** [comment]
no longer relevant
