### ISSUE TITLE
Dark theme/toggle

### ISSUE THREAD

**Issue by yujiaen1999** [cse110-sp23-group3/cse110-sp23-group3#71]
Design a version of dark theme based on ui-v2

**Comment by fnriv** [comment]
I think we have some sort of a dark theme [going here](https://github.com/cse110-sp23-group3/cse110-sp23-group3/issues/46#issuecomment-1575177302):

I think the sidebar text will need to be changed but at the least with the background choice? any opinions?

**Comment by yujiaen1999** [comment]
@fnriv ^

Yes, I see this. 
Anh already updated some part of the light theme. And I think dark theme is not only changing the bg, but also need some adjustment with the bubbles and font color. So I just try to implement another dark theme based on our most updated ui version (I think it is...)

**Comment by yujiaen1999** [comment]
<img width="1237" alt="Screen Shot 2023-06-06 at 21 41 41" src="https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/47964649/ba17c5e7-9555-4ccb-aa8b-4bc6c8d169c8">

I made a dark mode for our app based on our new light theme. I think we can do a switch function in setting as we mentioned in the discussion with prof. Need some feedback or suggestions for this dark theme. Much appreciated!
- Background: dark theme, less brightness, more contrast
- chat bubble: dark mode
- simba: dark bg
- buttons: dark mode

**Comment by fnriv** [comment]
I have a couple points of suggestions
- not sure if this was established with @MichaelYe48 but the for the chat name pencil, i think it should be on the other side of the side bar, not directly next to the name. i think pencil icon should be white too
- i also was wondering if we could make the color of the purple buttons a bit lighter? it kinda melts into the screen on the darker area. maybe make the gradient slightly lighter (ie dark (#4c337d) to light (#8e57aa))
- the new chat button on the light mode has a yellow outline and text, i think we could keep it the same in dark mode too

**Comment by yujiaen1999** [comment]
> I have a couple points of suggestions
> 
> * not sure if this was established with @MichaelYe48 but the for the chat name pencil, i think it should be on the other side of the side bar, not directly next to the name. i think pencil icon should be white too
> * i also was wondering if we could make the color of the purple buttons a bit lighter? it kinda melts into the screen on the darker area. maybe make the gradient slightly lighter (ie dark (#4c337d) to light (#8e57aa))
> * the new chat button on the light mode has a yellow outline and text, i think we could keep it the same in dark mode too

The pencil was established by Michael. And it's an icon photo, so i don't think I can change its color. But we can try to some other similar icon in both black and white. Yes, I make the color of button to be lighter. And I do change the chat button to have a purple outline and white text to make sure they fit the dark mode and have good readability. Here is what they look like now.
<img width="170" alt="Screen Shot 2023-06-07 at 00 42 31" src="https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/47964649/2cb5cad3-6c5f-4321-8679-948b49099e51">
<img width="180" alt="Screen Shot 2023-06-07 at 00 42 35" src="https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/47964649/3ee8d225-5a20-4260-9bfb-0a059073f5a7">
<img width="106" alt="Screen Shot 2023-06-07 at 00 42 39" src="https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/47964649/ebfa7965-ea81-4c68-bf0e-00ef08e30354">

**Comment by yujiaen1999** [comment]
<img width="1238" alt="Screen Shot 2023-06-07 at 00 46 08" src="https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/47964649/d859e41b-4bae-4ba0-be26-0f408393987c">

Changed the color of buttons to be lighter. More clear and better readability.

**Comment by phuanh004** [comment]
I'll work on this on the next version

**Comment by henryzhang03** [comment]
@phuanh004 we really need this ASAP to fit the CRUD criteria, can you look at the ui-v2-dark branch and make it consistent with the ui-v2? Then instead of a "settings" button we can do a toggle like

![image](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/34951639/21dba9d2-ef6a-4457-a7d2-5eac5420f5d8)

I can add the functions to call to update local storage, or you can, just let me know.

**Comment by phuanh004** [comment]
@henryzhang03 

I am thinking about having settings in the chat like this:

<img width="1170" alt="Screenshot 2023-06-07 at 3 05 12 PM" src="https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/9192184/9adda1b3-b3ba-448a-ac08-f36d1c8b4edf">


```html
<div class="message-bubble">
    <p class="message-text text-md">
    </p><table>
        <tbody><tr>
            <th class="message-text text-md">Settings</th>
        </tr>
        <tr>
            <td class="message-text text-md">Theme</td>
            <td class="message-text text-md">: dark</td>
        </tr>
        <tr>
            <td class="message-text text-md">Language</td>
            <td class="message-text text-md">: English</td>
        </tr>
        <tr>
            <td  class="message-text text-md">Font Size</td>
            <td  class="message-text text-md">: medium</td>
        </tr>
    </tbody></table>
    <p></p>
</div>
```

What do you think?

**Comment by phuanh004** [comment]
Also, this is an easy implemented way with local storage.

https://www.ditdot.hr/en/dark-mode-website-tutorial

**Comment by yujiaen1999** [comment]
> @phuanh004 we really need this ASAP to fit the CRUD criteria, can you look at the ui-v2-dark branch and make it consistent with the ui-v2? Then instead of a "settings" button we can do a toggle like
> 
> ![image](https://user-images.githubusercontent.com/34951639/244207555-21dba9d2-ef6a-4457-a7d2-5eac5420f5d8.png)
> 
> I can add the functions to call to update local storage, or you can, just let me know.

@phuanh004  I think this is a more concise and easy-to-use way for the switch. Personally i will prefer this one.

**Comment by nsyousef** [comment]
I agree with @yujiaen1999's point about the dark mode toggle. However, an argument that can be made for Anh's design is that it is more conducive to allowing new features to be added later. I remember Professor Powell said in lecture that it can be good for us to show that we are thinking of features that could be added later, if we had more time to work on the project or if someone else were to take over. If we were to use Anh's design because of that, though, we would have to make sure the rest of our code also allows for it to happen easily. For instance, we would need a 2D array to hold the default fortunes that can be indexed by language to allow for other languages to be added to the future. I don't know if just having a UI element to change the language but no clear way to implement the feature under the hood would cut it.

**Comment by phuanh004** [comment]
Alright, so the question is do we want to extend the settings function further?

If not, then I would keep it easy as a toggle button at the top right, probably since we are already cramming a lot of things on the sidebar.
If yes, then would we replace the whole app container with the new settings or just have it in chat?

**Comment by nsyousef** [comment]
At this point, it would probably be safest to just have the toggle. That way, we don't increase the scope too much and end up not meeting the coding deadline. Plus I know people probably have finals and things for other classes to get ready for, so it might be wiser to just keep it simple. Make sure everything is polished, our code is documented and tested, the repo is clean, etc. as opposed to adding a bunch of settings features.

**Comment by yujiaen1999** [comment]
![image](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/47964649/ba274294-1e3c-4ec8-b641-343e81ba81b1)
![image](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/47964649/c620cbad-3bf1-4e9b-99ba-004df099db61)

Currently, we don't have any other settings except the mode switch. But it's possible to have in future(we are not going to  implement now). So my suggestion is keep the <setting button> in sidebar for future possible work. And add a separate mode switch toggle above the <setting button> or at the top right. Because this toggle will be use frequently, and many good apps also make it a individual button apart from other settings.

**Comment by nsyousef** [comment]
I personally am fine with either keeping the switch in the sidebar or putting it in the top right. Keep in mind the About Us page does not have a sidebar, so if we want the toggle to appear on that page, we need to either add a sidebar to it or put the toggle in the upper right corner. Or we can just not have a way to toggle the light/dark mode on the About Us page.

**Comment by phuanh004** [comment]
@yujiaen1999 

Do you have one in some good "app" that has both settings and a separate toggle btn for light/dark mode? It is a terrible design and easy to mess up the code further.

**Comment by yujiaen1999** [comment]
I'm not sure which app it is. But I'm ok with that design personally. If you want to put the toggle inside the setting or just remove the setting. That's totally fine.

**Comment by henryzhang03** [comment]
Imo it's getting close to the end date, we should get it done ASAP so a toggle is the best choice.

**Comment by phuanh004** [comment]
@henryzhang03 got it

Does anyone want to take a part on the `localStorage` code on this [write-up (@Addition: How to Make Persistent User Choice Mode with JavaScript using localStorage)](https://www.ditdot.hr/en/dark-mode-website-tutorial)?

- Just call the button `#mode-toggle` or something like that then I will hook it up with the UI later

**Comment by phuanh004** [comment]
UI is now like this with the latest commit

![Screenshot 2023-06-07 at 7 41 44 PM](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/9192184/031ba71b-fba5-40f2-86c0-b19248152d93)

**Comment by nsyousef** [comment]
I don't know if you all are aware of this or not, but I figured I would make a note of a bug with the dark theme. If your operating system is in dark mode and you navigate to the homepage of our site, either in the `v2.0.1` branch or in the `main` branch (using LiveServer; the GitHub pages site has another issue: #82), the page loads in dark mode, but the switch is set to light mode, as in the picture below:

<img width="1792" alt="Screenshot 2023-06-08 at 4 07 34 PM" src="https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/114201888/b0a654d9-f962-48b7-a480-b91abc20269b">

When you click the switch, the theme does not change if your operating system is in dark mode. This issue does not occur if your operating system is in light mode.

**Comment by phuanh004** [comment]
@nsyousef 

Interesting, cus right now, it keeps track of both OS and CSS, so this causes the problem. Usually the dark/ light mode. Must have a variable to keep track of user's option, either automatic/dark/light.  But we do not have it yet.

So, for the quick solution, I will get rid of the automatic one.

**Comment by phuanh004** [comment]
@nsyousef can you check if it is fixed?

**Comment by nsyousef** [comment]
Sure. Which branch did you commit it to? `v2.0.1` or `ui-v2-dark`?

**Comment by phuanh004** [comment]
@nsyousef `v2.0.1` with the above's commit

**Comment by nsyousef** [comment]
So, it sort of works better. Now, when I load the page with my laptop in dark mode, the page shows up in dark mode. The switch shows the sun icon (shouldn't it show the moon icon?). When I flip the switch, the page changes to light mode and the switch changes to the moon icon. However, if I refresh the page while the page is in light mode (and my OS is in dark mode), it switches back to dark mode instead of staying in light mode.

When I load the page with my laptop in light mode, it shows up in light mode and the switch is set to the sun icon. When I flip the switch, the page switches to dark mode and the switch shows the moon icon. If I refresh the page with the website in dark mode but my laptop's OS setting in light mode, the page switches back to light mode.

**Comment by phuanh004** [comment]
@nsyousef it should work like that. Changing to not depend on the OS cause more trouble then what I thought. Check the latest commit again! Thank you!

**Comment by nsyousef** [comment]
The switch is working properly now.

Oh ok. So it is just supposed to conform to the OS setting when you reload? Because I still see something being saved to local storage that stores whether it is light or dark. Is that supposed to still be there or is that just a leftover from when we did try to save the user's preferences?

Also, if we are not saving this setting, then what is our 'update' in CRUD? Is that just renaming the chats instead of this?

**Comment by phuanh004** [comment]
Like Henry mention above, we decided to use this one for update, but since we already have the rename update, we can go with the rename for the update in CRUD then.

For the above question related to the OS conform, so right now, I still respect the OS settings, because my code used to depend on that at the beginning then. Better not risk changing too much on it.
